// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.History", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("calories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("carbs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fats")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("protein")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Histories", (string)null);
                });

            modelBuilder.Entity("Domain.Models.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MealPlan", (string)null);
                });

            modelBuilder.Entity("Domain.Models.MealPlans", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("TabName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.ToTable("MealPlans", (string)null);
                });

            modelBuilder.Entity("Domain.Models.MealRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<int>("Carbs")
                        .HasColumnType("integer");

                    b.Property<int>("Fats")
                        .HasColumnType("integer");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MealPlansId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealPlansId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealPlansId2")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealPlansId3")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealPlansId4")
                        .HasColumnType("uuid");

                    b.Property<int>("Protein")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealPlansId");

                    b.HasIndex("MealPlansId1");

                    b.HasIndex("MealPlansId2");

                    b.HasIndex("MealPlansId3");

                    b.HasIndex("MealPlansId4");

                    b.ToTable("MealRows", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("openWelcome")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Models.UserDetail", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<int>("bmr")
                        .HasColumnType("integer");

                    b.Property<int>("carbsGrams")
                        .HasColumnType("integer");

                    b.Property<int>("dailyCalories")
                        .HasColumnType("integer");

                    b.Property<int>("fatGrams")
                        .HasColumnType("integer");

                    b.Property<int>("percentCarbs")
                        .HasColumnType("integer");

                    b.Property<int>("percentFat")
                        .HasColumnType("integer");

                    b.Property<int>("percentProtein")
                        .HasColumnType("integer");

                    b.Property<double>("poundsToLoseGainPerWeek")
                        .HasColumnType("double precision");

                    b.Property<int>("proteinGrams")
                        .HasColumnType("integer");

                    b.Property<string>("rateOfFatLossMuscleGain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("tdee")
                        .HasColumnType("integer");

                    b.Property<bool>("userStatsExist")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("UserDetails", (string)null);
                });

            modelBuilder.Entity("Domain.Models.MealPlans", b =>
                {
                    b.HasOne("Domain.Models.MealPlan", "MealPlan")
                        .WithMany("Plans")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("Domain.Models.MealRow", b =>
                {
                    b.HasOne("Domain.Models.MealPlans", "MealPlans")
                        .WithMany()
                        .HasForeignKey("MealPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.MealPlans", null)
                        .WithMany("BreakfastRows")
                        .HasForeignKey("MealPlansId1");

                    b.HasOne("Domain.Models.MealPlans", null)
                        .WithMany("DinnerRows")
                        .HasForeignKey("MealPlansId2");

                    b.HasOne("Domain.Models.MealPlans", null)
                        .WithMany("LunchRows")
                        .HasForeignKey("MealPlansId3");

                    b.HasOne("Domain.Models.MealPlans", null)
                        .WithMany("SnacksRows")
                        .HasForeignKey("MealPlansId4");

                    b.Navigation("MealPlans");
                });

            modelBuilder.Entity("Domain.Models.MealPlan", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("Domain.Models.MealPlans", b =>
                {
                    b.Navigation("BreakfastRows");

                    b.Navigation("DinnerRows");

                    b.Navigation("LunchRows");

                    b.Navigation("SnacksRows");
                });
#pragma warning restore 612, 618
        }
    }
}
